services:
  db:
    ports: [ "5432:5432" ]
  cache:
    ports: [ "6379:6379" ]
  storage:
    ports: [ "9000:9000", "9001:9001" ]
  migrate:
    build: .
    image: eventhub-api:local
  api:
    image: eventhub-api:local